# Site settings
title: WebKitGTK
url: "https://webkitgtk.org" # the base hostname & protocol for your site
sourceurl: "https://github.com/WebKitGTK/webkitgtk.org" # "edit this website" link in the footer
description: "A WebKit port for the GTK library."
issuesurl: "https://github.com/WebKitGTK/webkitgtk.org/issues" # issue tracker for website
permalink: /:title/
markdown: kramdown
